### PR TITLE
Added LFE support.

### PR DESCRIPTION
**Pull request by oubiwann**
Very excited about this project! LFE on ARM will be fantastic :-)

LFE infos:
 * https://github.com/rvirding/lfe
 * http://lfe.io/
 * http://docs.lfe.io/

If this eventually gets the stamp of approval, do you think we could update the nerves-sdk Github description to the following?

"Platform infrastructure for embedded Erlang/OTP, Elixir and LFE projects"

### CODE REVIEW

**Comment by fhunleth** [comment]
Sorry for the super long wait. I've played around with LFE enough to know that it works in Nerves, so I committed your patch to master. It's not easy to use LFE in Nerves yet, but that shouldn't delay getting your patch in. I'm working on making it simpler to use LFE, and then I'll start updating all of the docs to show how to use it. Thank you again for sending this over.

**Comment by oubiwann** [comment]
No worries about the delay at all! This is suuuuper exciting news :-) I'm going to cc @rvirding so he knows, too :-)

This just pushed a beagle bone cluster to the top of my wish list ... can't *wait* to try it out (and hopefully help make LFE much easier to use in Nerves ...).

Thanks for the testing and the merge!

**Comment by fhunleth** [comment]
Give me a little bit to make things easier. I think that it might be frustrating at the moment, since I had to make some tweaks to get the LFE REPL going and I haven't committed those. When I thought that I just was going to support Erlang, things weren't too hard, but now with Elixir and LFE, it's a little ugly. Also, if you have a Raspberry Pi, that will work too and I've been focusing on RPi support recently since I had some interest from a local company for using one in a product. RPi is a little slower, but I've been surprised by how well it works. I'm using a Model A+ for the Erlang Factory talk.

**Comment by oubiwann** [comment]
Cool -- I'll see if I can bring one my Raspberry Pi's back from the dead ...

Looking forward to your talk at EF SF!

**Pull request closed without merging**
